//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://AutoFXProfitsServer", ConfigurationName = "ITradeMirror", CallbackContract = typeof(ITradeMirrorCallback), SessionMode = System.ServiceModel.SessionMode.Required)]
public interface ITradeMirror
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://AutoFXProfitsServer/ITradeMirror/Subscribe", ReplyAction = "http://AutoFXProfitsServer/ITradeMirror/SubscribeResponse")]
    string Subscribe(string userName, string password, int accountID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://AutoFXProfitsServer/ITradeMirror/Unsubscribe", ReplyAction = "http://AutoFXProfitsServer/ITradeMirror/UnsubscribeResponse")]
    bool Unsubscribe(string userName, string password, int accountID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://AutoFXProfitsServer/ITradeMirror/PublishNewSignal", ReplyAction = "http://AutoFXProfitsServer/ITradeMirror/PublishNewSignalResponse")]
    void PublishNewSignal(string signalInformation);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITradeMirrorCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://AutoFXProfitsServer/ITradeMirror/NewSignal")]
    void NewSignal(string signalInformation);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITradeMirrorChannel : ITradeMirror, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TradeMirrorClient : System.ServiceModel.DuplexClientBase<ITradeMirror>, ITradeMirror
{

    public TradeMirrorClient(System.ServiceModel.InstanceContext callbackInstance) :
        base(callbackInstance)
    {
    }

    public TradeMirrorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
        base(callbackInstance, endpointConfigurationName)
    {
    }

    public TradeMirrorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public TradeMirrorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public TradeMirrorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, binding, remoteAddress)
    {
    }

    public string Subscribe(string userName, string password, int accountID)
    {
        return base.Channel.Subscribe(userName, password, accountID);
    }

    public bool Unsubscribe(string userName, string password, int accountID)
    {
        return base.Channel.Unsubscribe(userName, password, accountID);
    }

    public void PublishNewSignal(string signalInformation)
    {
        base.Channel.PublishNewSignal(signalInformation);
    }
}
